# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # Build the dist folder and push to gh-pages branch
      - run: pwd
      - run: git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
      - run: git config --global user.name "$GH_NAME" > /dev/null 2>&1
      - run: yarn styleguide:build
      - run: git add -A
      - run: git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
      - run: git push --force --quiet origin gh-pages
      - run: echo Success!

